### ISSUE TITLE
C1.19 HRS and relapse

### ISSUE THREAD

**Issue by emeijerperfectfit** [PerfectFit-project/testing-tickets#10]
tested by m.h.m.van_vliet@lumc.nl 26-05-2023; 10:59 to 11:47 
(similar issues encountered by other tester emmafranca@gmx.de 26-05-2023 around 14.00)

The coach sends things like “Je hebt aangegeven dat je 1 hebt gerookt. Klopt dat? Typ ja of nee”. Two issues with this:
- I can't find this in the excel file so I'm not sure whether the most recent version of the dialog was implemented. For example row 89 was deleted by Milon and this message sent by Sam seems to be similar. Also for row 100 for example the 9th option doesn't seem to be implemented. Please check whether the adjustments suggested by Milon (in column E in the excel file) were implemented
- If it is somewhere in the dialog but I just couldn't find it; the number should be replaced by what it stands for (in this case it should read something like Je hebt aangegeven dat je sigaretten hebt gerookt)
This issue also showed up in feedback by the 2 testers of the weekly reflection dialog from when they were redirected to part of the HRS dialog; so not specific to Milon.

Row 89: the coach sent "Om hiervan te leren helpt het om te kijken naar de situatie(s) waarin je toch weer ging roken. Daarom wil ik je daar wat vragen over stellen" and then row 90 "Daarom wil ik je daar wat vragen over stellen" in the next message. "Daarom wil ik je daar wat vragen over stellen" should be removed from row 89 (is also not shown included in row 89 the excel)
Row 115: similar issue, part of the text seems to be sent twice. “Ik raad je aan om meteen weer te stoppen. Wat kan helpen…. Het kan ook helpen om te praten met bijvoorbeeld een vriend of familielid over hoe het is gegaan en je plan om opnieuw te stoppen.” and after that the message “Het kan ook helpen om te praten met bijvoorbeeld een vriend of familielid over hoe het is gegaan en je plan om opnieuw te stoppen.” 

Just to check: graph with high risk situations in not adapted to answers in the dialog right? otherwise algorithm doesn't work properly

After 43 mins Milon had indicated that she wanted to see her ehbo-doos (first aid kit). The coach sent “Sorry, ik begrijp (nog) niet wat je bedoelt, kun je me het op een andere manier duidelijk maken?” after Milon had indicated that she was done with the ehbo-doos by sending 1 (as requested by the coach)
Emma had something similar with this Sorry message appearing, see below in screenshot; 11 mins after the start of the dialog

![image](https://github.com/PerfectFit-project/testing-tickets/assets/135458606/bc19ad87-3a37-4388-bb0d-7ff07db81a2c)

Emma noticed that the dialog stopped when she choose to do activity nr 4 (see screenshot). The dialog continued when she chose activity 1 and 5. 
She was in the PA tracked, but activity 2 was not suitable for PA. Please check whether suggested activities fit smoking / PA
![image](https://github.com/PerfectFit-project/testing-tickets/assets/135458606/88c49a1a-3395-4a53-b01c-7efaf664886a)

**Comment by wbaccinelli** [comment]
@emeijerperfectfit from the testing time reported, I see that the dialog was tested before it was ready (I reported that the dialog was ready to be tested at 17.38 on May 26th). This means that a very old nd not adapted version of the dialog has been run. For example, I guess that the emojis were not included. Most of the issues might not apply anymore, and new ones might be there. I strongly suggest to re-test it in its final version.

**Comment by emeijerperfectfit** [comment]
Will do! Both Anke and I will test the intervention for a couple of weeks so this will definitely come by
