### ISSUE TITLE
Sorry ik begrijp (nog) niet wat je bedoelt message

### ISSUE THREAD

**Issue by emeijerperfectfit** [PerfectFit-project/testing-tickets#11]
The 'Sorry ik begrijp (nog) niet wat je bedoelt’ response should not be triggered when people send something (that the coach doens't understand) during a dialogue with the coach. For example in some dialogs the coach says something that people may respond to, e.g. "Weet je nog hoe dat er uit zag? Probeer dat weer voor je te zien." (and people might say yes) or ""Succes, je kan het!" (and people might say thanks). If the coach then sends the sorry message with all the options, that's confusing

I think it’s better if the coach ignores the user's message and just continues with the dialogue; and save the Sorry message for when people start typing things outside of a dialog. If the user is supposed to say something within a dialogue (e.g. type 1 for this 2 for this etc) and type something else, the response seems ok (i.e. answer options are repeated).

![image](https://github.com/PerfectFit-project/testing-tickets/assets/135458606/307bd24a-311e-42ea-a5a9-42061a2440f6)

**Comment by emeijerperfectfit** [comment]
For notifications, it's also confusing if the VC sends the Sorry etc message after people respond to the notification. It's better if the VC then repeats the message that instructs users what to send (e.g. 'Typ verder als je klaar bent om verder te gaan)

**Comment by wbaccinelli** [comment]
@emeijerperfectfit If the VC responds with the Sorry message is indeed a bug. It should not happen inside a dialog. In the example you reported, this happens because of the 10s delay. In those 10s the user is actually out of the dialog. A solution would be to get rid of that delay. Could that work?

**Comment by wbaccinelli** [comment]
> For notifications, it's also confusing if the VC sends the Sorry etc message after people respond to the notification. It's better if the VC then repeats the message that instructs users what to send (e.g. 'Typ verder als je klaar bent om verder te gaan)

@emeijerperfectfit A response to the notifications is not expected. The moment the notification is sent, the dialog ends. If an answer is expected, the dialog will hang for 1h and a response is then mandatory. Let me know which is the solution you prefer.

**Comment by emeijerperfectfit** [comment]
Hi Walter, in some dialogs we do need the delay (e.g. 10 sec) to sort of force people to think about something, they won't do that if the dialog just continues. Would it be possible to disable the Sorry reponse during these delays? I believe that only a few dialogs have this

**Comment by emeijerperfectfit** [comment]
Would it be an option to disable the Sorry response for about 1 minute after people have read a notification? Or do you think that people will then need the menu and won't get it?

**Comment by wbaccinelli** [comment]
I am not sure if it is possible to disable the responses. I will look into it, hopefully it is not too complicated

**Comment by wbaccinelli** [comment]
Good news! It is possible to pause and resume the conversation, I am implementing it
