### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by emeijerperfectfit** [PerfectFit-project/testing-tickets#13]
C1.24 
In the second message, it is now mentioned that they can see in their watch the number of minutes of intense physical exercise preformed. Please refer to the manual as well (for information on how to do so). Second message of notification C1.22 could be used for this, from “Uitleg over ….. Perfect Fit programma.” and add this after "Kijk dan op je horloge."

C1.27 
Change last message and remove ‘Je kunt mij ook altijd een berichtje sturen. Ik sta voor je klaar!” 
C1.29
Change last message and remove ‘Je kunt mij ook altijd een berichtje sturen, mocht je me nodig hebben.”

**Comment by bscheltinga** [comment]
C1.24 is de reminder voor het afmaken van een dialoog. Ik zie niet waar hier wordt genoemd dat ze het aantal intensieve minuten kunnen zien op het horloge.

**Comment by bscheltinga** [comment]
Bij C1.27 zie ik de zin "Je kunt mij ook altijd een berichtje sturen. Ik sta voor je klaar!" uberhaupt niet. Dit is bij mij de setp goal & intensive PA notification.

C1.29 is voor mij de 'New quit date notification', daarin zit ook niet de zin die jij hierboven noemt.

Ik gebruik de conventie hoe de bestanden op teams staan in Documents -> Genaral -> Content folder -> Virtual Coach Dialogs and Resources -> 4- Other messages

**Comment by aversluis1** [comment]
[dialogs_testing_status.xlsx](https://github.com/PerfectFit-project/testing-tickets/files/11788098/dialogs_testing_status.xlsx)

**Comment by aversluis1** [comment]
Dit is het document wat ik heb gebruikt voor het testen van de notificaties, hierin staat vermeld waar de nummers naar refereren.

**Comment by aversluis1** [comment]
Heb je hier voldoende aan?

**Comment by bscheltinga** [comment]
> Heb je hier voldoende aan?

Ja. Er zit inderdaad verschil tussen de lijsten met dialoogcodes (C1.xx) die wij hadden. Het is nu wel duidelijk.
