### ISSUE TITLE
180 messages about video

### ISSUE THREAD

**Issue by emeijerperfectfit** [PerfectFit-project/testing-tickets#14]
![Screenshot_20230608-060814](https://github.com/PerfectFit-project/testing-tickets/assets/135458606/071ff42c-6131-4b00-85ed-bfbda1df4fed)

My app kept sending these messages about a video, each night around 2 AM, and notified me that I had about unread 180 messages. I had not opened the app in between
Account e.meijer@lumc.nl

**Comment by wbaccinelli** [comment]
this goes together with #15
