### ISSUE TITLE
Notifications overload

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#15]
On june 5th, I checked the notification for quite date. This went fine. But.. at 2:01 in the morning, I continue to receive about 40 messages -- see screenshot

This has been happening for 3 nights in a row now

![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/5808755b-2bc2-4c6b-9299-8e0dc19f8537)
![2](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/5401180e-b95d-4c25-97bc-a30f2c26235f)

**Comment by wbaccinelli** [comment]
Oh, this is very bad! I suggest to switch off notifications for the NiceDay app for the moment 😅

**Comment by aversluis1** [comment]
Haha, will do
