### ISSUE TITLE
Getting started issues

### ISSUE THREAD

**Issue by emeijerperfectfit** [PerfectFit-project/testing-tickets#18]
Morning, I've just started testing on my previous phone, account eline.meijer@hotmail.com. 
I encountered some issues:

- 18/7 8.10 after the profile creation I was asked whether I wanted to do an exercise and got a menu with 5 options (1 om een oefening over jezelf te doen, 2 als je weetjes wilt; and so on). I chose 2 and then I got these messages: "Super ! Dan kun je kiezen uit de volgende oefeningen: [empty]" and "Typ 1 als je toch een andere soort oefening wilt doen". I typed 3 and then I got "Kun je een geheel getal tussen 1 en 1 opgeven? ..." and again "Typ 1 als je toch een andere soort oefening wilt doen". I typed 1 and then I got the menu with 5 options from the start. I chose 1, and then I could select an exercise which also started as it should, but something goes wrong with the menu here

- I got the exercise Korte film in je hoofd (future self short), but this should only be offered after they've done the long version in the past (either by choice through this menu, or suggested by the coach). Otherwise they miss crucial instructions, and the short future self video also refers back to what they've done in the long version. 

- After installing niceday and connecting with sam, the conversation starts with "Je gaat nu een video bekijken" (it's the watch this video dialog). That is odd as people have not interacted with Sam before. After watching the video I got the question whether I wanted to do the next part now or later, and when I said now I got "Super dan gaan we beginnen!" and "Hallo" and "Welkom bij het Perfect Fit programma!" It would make more sense to start the conversation (as the very first message) with Hallo and Welkom bij het Perfect Fit programma; and then show the video

**Comment by wbaccinelli** [comment]
For point 3: I will remove the sentences: "Hallo" and "Welkom bij het Perfect Fit programma!" from the profile creation, and put them before the introduction video
