### ISSUE TITLE
HRS dialog PA

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/testing-tickets#21]
Date: 19th July 2023
Context: I typed "help" to start the HRS dialog during the preparation phase and then indicated that it is about PA.

1) It should say "Wat heb je verder gedaan overdag" but says "Wat heb je verder overdag?": 
![WhatsApp Image 2023-07-19 at 2 35 33 PM (1)](https://github.com/PerfectFit-project/testing-tickets/assets/43779515/f10db28e-4fed-4ff7-bb48-f12cb9b769c4)

2) There is an extra "Wat heb je verder overdag" after "Bedankt voor het open zijn over wat er gebeurde" that should not be there: 
![WhatsApp Image 2023-07-19 at 2 35 33 PM](https://github.com/PerfectFit-project/testing-tickets/assets/43779515/688b078a-af7d-4f3c-b705-8f514ff15f44)

3) Option 4 about having now enough motivation to stop with smoking sounds weird since I has asked for help for not doing PA: 
![WhatsApp Image 2023-07-19 at 2 35 32 PM (1)](https://github.com/PerfectFit-project/testing-tickets/assets/43779515/d71b0ba5-acdd-45d5-a394-5b1ec8baf679)

4) I am asked to type "Oefening" to do an activity after being told that there is nothing yet in my first aid kit, but then I do not get a chance to type "oefening". Instead, a new message comes that asks me to type 1 or 2. So I had no chance to do an activity: 
![WhatsApp Image 2023-07-19 at 2 35 32 PM](https://github.com/PerfectFit-project/testing-tickets/assets/43779515/42669f40-f4cb-4855-bee8-a33960ff964c)

**Comment by nelealbers** [comment]
@emeijerperfectfit, could you look at points 1 and 3 above? They relate to content in the HRS dialog for PA.

**Comment by emeijerperfectfit** [comment]
Hi Nele, agree that this should not go this way. I agree with your suggestions (also for point 2 and 4). For point 3 this should be 'om te gaan bewegen' instead of 'om te stoppen met roken'.
We no longer make changes to the excel files, but I'd think that these things can be implemented directly.

**Comment by nelealbers** [comment]
@emeijerperfectfit, sounds good!

**Comment by emeijerperfectfit** [comment]
And something else about the HRS dialog (I did it for smoking), i.e. the message where the VC asks about emotions (with all the emoticons in it for blij, verdrietig etc).
- The first sentence is included twice
- I think the crying emoticon should be replaced by a sad face :( This one has waterfalls of tears and I’m afraid users won’t feel taken seriously
- I did not have time to answer as the message asking about emotions was directly followed by the one about ‘Met wie was je toen je trek kreeg’. And then my answers became mixed up. This could be a synchronizing error in the app in general but data was not saved correctly

**Comment by nelealbers** [comment]
@emeijerperfectfit I fixed the crying emoji. I cannot reproduce the part about the first sentence being included twice. Which sentence exactly do you mean?

**Comment by emeijerperfectfit** [comment]
@nelealbers thanks! It’s just a content thing, a message in the HRS branch for smoking and then the first option (urge to smoke) has the same sentence twice at the start. See screenshot; it’s the message that asks the user how they felt when they wanted to smoke
![Screenshot_20230727-172826](https://github.com/PerfectFit-project/testing-tickets/assets/135458606/cc464077-878a-4a7e-8b32-1a65b27578f1)

**Comment by emeijerperfectfit** [comment]
In the PA HRS dialog I first got a message from the coach that he did not understand what I meant (when I have to describe how I feel watching the picture with reasons for physical inactivity). After the conversation below I got the entire menu with the commands like help oefening verder etc

![Screenshot_20230727-214625](https://github.com/PerfectFit-project/testing-tickets/assets/135458606/56b9a0d3-a7b7-445b-9609-e8b279d00c77)
