### ISSUE TITLE
Reminders to complete dialogs at 1:50am

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/testing-tickets#24]
I got a reminder to complete a video-watching dialog at 1:50am. Would it be possible to not send reminders between say 12am and 5am when most people would be sleeping?

![WhatsApp Image 2023-07-21 at 8 37 09 AM](https://github.com/PerfectFit-project/testing-tickets/assets/43779515/195613a1-b6f7-4726-acb2-09c0e3d874dc)

**Comment by emeijerperfectfit** [comment]
Same happened here, I would actually stretch the "sleep period" a bit, say from 10PM to 7AM?

**Comment by emeijerperfectfit** [comment]
I also got a message from a tester who got an exercise at 6 AM when she was asleep, but she could only continue with this after she had gone through the sorry menu - which she found annoying, and I think it doesn’t help for bonding with the coach. I think we should not send anything between 10pm and 7am, and perhaps also (but not sure how that would affect the rest of the intervention) allow people a bit more time to respond to a message from the coach.
