### ISSUE TITLE
Initially incomplete self-initiated HRS dialog keeps being available via 'verder' after completion

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/testing-tickets#26]
I did not complete the HRS dialog. I restarted it via 'verder' and completed it. But if after completing I type 'verder', the HRS dialog starts again. So it seems that the dialog is not marked as completed:

![WhatsApp Image 2023-07-21 at 10 27 11 AM](https://github.com/PerfectFit-project/testing-tickets/assets/43779515/2dcc41f7-f85c-4335-b030-4dcb58039d65)

**Comment by wbaccinelli** [comment]
@nelealbers di you start it multiple times? It is also a case that should be actually managed

**Comment by nelealbers** [comment]
@wbaccinelli Possible. I also completed it about 5 times though and it was still available via 'verder'. Not sure if I started it more than 5 times.
