### ISSUE TITLE
Uncompleted HRS dialog seemly starts itself

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/testing-tickets#29]
An uncompleted HRS dialog seemingly started itself:

![WhatsApp Image 2023-07-22 at 11 52 26 PM](https://github.com/PerfectFit-project/testing-tickets/assets/43779515/8afcdbd2-495d-41d3-a54c-60262bc2a483)

![WhatsApp Image 2023-07-22 at 11 52 26 PM (1)](https://github.com/PerfectFit-project/testing-tickets/assets/43779515/9f689fd2-79ff-475e-b307-799b34bb37ac)

**Comment by wbaccinelli** [comment]
@nelealbers in general, the uncompleted dialogs follow this schema: if a dialog has not been completed, after 1h the user receives a notification telling him/her to type 'verder' to resume and complete the dialog. After another 1h and half, if the dialog is still to be completed, it's execution is scheduled for the next day. We can also get rid of this last part of the behavior.

**Comment by nelealbers** [comment]
@wbaccinelli I think we can keep this. I created an issue to just reformulate the initial statement of the HRS dialog so that it does not seem like the user asked for help when they did not (https://github.com/PerfectFit-project/virtual-coach-issues/issues/395). And then together with the issue about not letting users continue an expired non-relapse HRS dialog, this should then be ok.
