### ISSUE TITLE
App is slow

### ISSUE THREAD

**Issue by emeijerperfectfit** [PerfectFit-project/testing-tickets#30]
I'm not sure whether this has anything to do with perfect fit but I notice on both the phones that I use for testing that the ND app is quite slow sometimes. Especially when I go to contacts and it has to make the connection with Sam again, it always says connecting..... for a while and then it also takes some time before all messages are shown. Sometimes I also get push notification of messages (e.g. typ 1 als de video duidelijk was, typ 2 etc) that are not shown in the dialog window

**Comment by wbaccinelli** [comment]
@emeijerperfectfit this is something that cannot be solved on our side.

**Comment by emeijerperfectfit** [comment]
Good to know!
