### ISSUE TITLE
Profile creation c

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#33]
![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/b6c422bc-5977-407a-aad5-c041b5a6cfe3)
![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/dbf8a795-5bad-4bd8-aaa9-28724a41b0d3)

![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/5507570e-a725-4266-803a-8192ca34cd1e)
![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/8ec5efe1-1c58-4d0b-a8e9-916c31f0f3a1)

**Comment by wbaccinelli** [comment]
@aversluis1 is it possible to know for which account and at what time the issue occurred? So I can see what happened.

For the bold or underlined words, I don't know if that is something we can include

**Comment by aversluis1** [comment]
@wbaccinelli , this was my account so a.versluis@lumc.nl. It occured on 24th of July at 10:08

**Comment by emeijerperfectfit** [comment]
My mother (janitameijer@hotmail.com account) managed to connect with Sam, then to get the video, and then she just continued with the verder messages and at some point the HRS dialog was triggered after she had typed ‘Ik wil nu stoppen met chatten’. But she had skipped the profile creation dialog altogether. I also saw that she had received the first welcoming messages (Hallo! Welkom bij Perfect Fit; or something like that) a couple of times on separate days.

She did reinstall the app as she thought something had gone wrong, perhaps something to do with that, but I’m afraid that many of our actual users have about the same digital skills as my mother

**Comment by wbaccinelli** [comment]
@emeijerperfectfit I took a look, at the conversation. She received the messages multiple times because she never completed the first dialog. to complete the video one must answer to the final question 'Typ '1' voor 'duidelijk' en '2' voor 'nog een keer bekijken'. So the first dialog (introductory video) will keep on being proposed by Sam, and the profile creation will not be shown unless this dialog will be completed.
