### ISSUE TITLE
Message after medication video

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#34]
![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/189ef5b3-3d88-4a44-b62a-370059ef4b58)
![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/ba994bff-fba5-4425-b6fc-04a9a49a605f)

**Comment by wbaccinelli** [comment]
That's actually the correct flow. @aversluis1 how do you propose to change this?

**Comment by aversluis1** [comment]
@wbaccinelli. Is it always the case that these dialogues are following each other up immediately? If so, I would remove the message that I crossed out in the screenshot.

**Comment by wbaccinelli** [comment]
@aversluis1 they will always follow each other immediately, but they can also be rescheduled for another time. It the latter case, they will start in the same way

**Comment by aversluis1** [comment]
@wbaccinelli , ah I see, then maybe better to leave it as it is.
