### ISSUE TITLE
2nd day ; notification timing

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#35]
![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/1a3aff99-4549-4a77-9005-5bf11483cbd4)
First question: maybe set time for first message later than 6 AM?, as majority will not be ready for exercises. 
Second question: reminder should be send later, not two hours after initial message. 

![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/a169a66d-5f18-404a-8c1c-95fa36b9761b)

**Comment by wbaccinelli** [comment]
Addressed here https://github.com/PerfectFit-project/virtual-coach-issues/issues/392
