### ISSUE TITLE
Question before exercise

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#37]
![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/c68dc74e-7200-4c0e-8692-cbdddc6d863c)
![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/1a1880e1-8afd-4f82-adc9-54f0075a318d)

Maybe irrelevant question/ If not, I would allow users to get away with a shorter answer (my answer was also to short to be accepted, which can cause frustration).

**Comment by wbaccinelli** [comment]
first note already [here](https://github.com/PerfectFit-project/testing-tickets/issues/28)

@aversluis1 we can get rid of the minimal length, but you have to decide on this point.

**Comment by aversluis1** [comment]
@wbaccinelli, I  think whether we want to change the minimal length depends on the conversation Nele and Eline are having regarding the question itself. If more information will be giving, than they might be able to answer the question and then the minimal length does not need to be addressed. I will post a message about this in the other ticket.

**Comment by wbaccinelli** [comment]
Ok, so I will close this issue.
