### ISSUE TITLE
C1.8 first aid kit

### ISSUE THREAD

**Issue by emeijerperfectfit** [PerfectFit-project/testing-tickets#4]
Tested by kbolt@trimbos.nl 25-5-2023 14:47 u

During an activity the question "Welke oefening wil je zien" was asked.

![image](https://github.com/PerfectFit-project/testing-tickets/assets/135458606/99be5003-e009-4750-9aae-f1a6debc5679)

**Comment by wbaccinelli** [comment]
@emeijerperfectfit is there a recording of this? I tried multiple times without being able to reproduce the behavior.

**Comment by emeijerperfectfit** [comment]
Unfortunately no, only these screenshots. Anke and I can check whether this shows up again when testing the entire thing
