### ISSUE TITLE
Execution problem

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#42]
User Josine Schaap (user name probably something similar) emailed me thursday that she is still experiencing trouble with the app. She is the one who had the problems with the 'verder' command -- see screenshot below. 

Now she mentions that she has restarted the app a couple of times, but nothing has chcanged. She has tried to say 'verder' more often, but nothing happens. When she says 'verder' at some point, Sam says she used a codeword to ask for help. She has not been able to continue. 

![Gesprek](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/ab519e19-ea4e-445b-9305-2589ef8db572)

**Comment by wbaccinelli** [comment]
Same as [this issue](https://github.com/PerfectFit-project/virtual-coach-issues/issues/398). 
Solved [here](https://github.com/PerfectFit-project/virtual-coach-rasa/pull/137) on 28/07/2023
