### ISSUE TITLE
EHBO command

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#46]
The ehbo command does not seem to work, if I type it I get the Sorry message and menu. This also makes it difficult to find an exercise I did before as it's no longer in the Oefening list 
Some exercises refer to another exercise (Ontspanning). I think we should add that Ontspanning is in the Oefeningen met handige tips category. However if they've already done this exercise there is no way to retrieve it at the moment since the ehbo command does not work (at least in my case)

Tester: Eline

**Comment by wbaccinelli** [comment]
- We decided, with Milon, to not make the ehbo available before the explanatory video has been shown. 
- The Ontspanning exercise is already in the Oefeningen met handige tips category.

**Comment by aversluis1** [comment]
* Okay, that makes sense. 
* regarding the exercise Ontspanning; I think what Eline meant is that it should be added to the text (when the text refers to the exercise 'ontspanning') that this can be found in the category ....

**Comment by wbaccinelli** [comment]
Ah ok, that is clearer now. But, please, indicate which resources need to be changed.

**Comment by aversluis1** [comment]
Honestly, I don't know in wat resources it is mentioned -- i will have a check

**Comment by aversluis1** [comment]
I found out: resources 2.5d and 2.5f. I have made additions in red in these dialogs.
