### ISSUE TITLE
Inaccurate codeword 

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#48]
I typed some nonsense and the coach stated that I had used my code word to ask for help and started the hrs dialog (see screenshot). I think that we should only use the specific commands for starting things 
Also there is no way to get out of the hrs dialog (which is really long) if it was unintended

![Screenshot_20230730-134029](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/734e8110-f2ba-4b8b-b950-03e513241687)

**Comment by wbaccinelli** [comment]
First point addressed [here](https://github.com/PerfectFit-project/virtual-coach-issues/issues/404)

@aversluis1 if one types 1, the next question includes the option to exit the dialog ('Typ '4' als je per ongeluk 'help' hebt getypt en nu geen hulp nodig hebt'). I agree that this would make more sense in the first question. Shall we move this?

**Comment by aversluis1** [comment]
Yes, I think that is a good idea. I was literally just starting a new issue regarding this. 

Two more questions regarding this: 
- I was in the same dialogue, but forgot to answer. I answered almost two hours after the question was asked (see screenshot). Is it correct that the dialogue then just ends on itself?
![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/f5b84f31-0a27-457b-b592-d93a2680c1e7)

- Next, the word options were given. Including the command 'verder' --> however, when I select it, the HRS dialogue starts again. Maybe better to say if this option is selected - and no dialogue is open - that there is no dialogue open? Is that possible? 

And my apologies if I keep asking the same questions, I sometimes lose track of what was discussed and what wasn't.

**Comment by aversluis1** [comment]
![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/8dfa92a4-6531-4e5a-aefe-00876d38a18b)

**Comment by wbaccinelli** [comment]
No problem.
The dialogs expire after 1.5 hours from the beginning, after 1h from the last answer, so you cannot continue but the defeult mode is triggered. This is to enable further conversations to happen, and to unload a bit the memory of Rasa. After a while you will get a notification asking you to type 'verder' to continue. But what actually happen with 'verder' ([for most of the dialogs](https://github.com/PerfectFit-project/virtual-coach-issues/issues/407#issuecomment-1658240051)), is that the dialog starts over. In your case, the last uncompleted dialog was the hrs, so it started again when you typed 'verder'.

**Comment by aversluis1** [comment]
i get it, but it is a bit confusing i think as a user. Maybe we can add a sentence after they type 'verder' and before the dialog starts, saying something like the dialog will continue now or be restarted from the beginning.  (Oké. Het dialoog waar je mee bezig was zal hierna weer verder gaan of, in sommige gevallen, weer starten vanaf het begin.

**Comment by wbaccinelli** [comment]
Yes, Nele and Eline discussed already this point for the HRS, see [this issue](https://github.com/PerfectFit-project/virtual-coach-issues/issues/395).  But it is actually a good idea to add an introductory sentence for the 'verder' command

**Comment by wbaccinelli** [comment]
Issue split and addressed in main issues repo.
