### ISSUE TITLE
C1.9 goal setting

### ISSUE THREAD

**Issue by emeijerperfectfit** [PerfectFit-project/testing-tickets#5]
tested by k.m.penfornis@fsw.leidenuniv.nl; 23 May 2023, 13:21
- Instead of picture showing different intensities of PA the apps notifies that ‘1 file has been deleted’ 
- After showing the second example goal the app did not do anything for about 10 sec after Kristell  had typed klaar
- if there is no sensor data for steps Sam says things like ‘in de afgelopen 9 dagen zette je ongeveer [insert average amount of steps during previous 9 days]] stappen per dag’ and ‘Daarom wordt je stappendoel voor morgen: [ insert 7th highest amount os steps during previous 9 days]. Is it possible to have something there that users understand? --> Check with Bouke

Row 107 in excel: numbers are shown now ("ik kan me voorstellen dat jouw 1/2/3/4 belangrijk voor je is/zijn. Kun je me iets meer vertellen over waarom dit doel belangrijk is voor jouw 1/2/3/4?" ), but here the meaning of the number should be inserted. For example "ik kan me voorstellen dat jouw familie belangrijk voor je is/zijn"

**Comment by nelealbers** [comment]
last point already covered in this issue: https://github.com/PerfectFit-project/virtual-coach-issues/issues/341

**Comment by wbaccinelli** [comment]
- First point already solved

- Third point to be addressed when sensors data will be available. Issues already opened [here](https://github.com/PerfectFit-project/virtual-coach-issues/issues/325) and [here](https://github.com/PerfectFit-project/virtual-coach-issues/issues/323)

**Comment by nelealbers** [comment]
Last point already covered here: https://github.com/PerfectFit-project/virtual-coach-issues/issues/341

**Comment by bscheltinga** [comment]
We should also be consistent with displaying dates. Thus: only using the 01-12-2023 or 01/12/2023 option, to prevent confusion.

**Comment by bscheltinga** [comment]
- I did not see the behaviour of the second point. (10s freeze after 2nd testimonial)

**Comment by emeijerperfectfit** [comment]
> * I did not see the behaviour of the second point. (10s freeze after 2nd testimonial)

I'm not sure why that is, but if you can't replicate this Anke and I can check whether this happens when testing the entire thing

**Comment by bscheltinga** [comment]
> We should also be consistent with displaying dates. Thus: only using the 01-12-2023 or 01/12/2023 option, to prevent confusion.

Created new issue for this: https://github.com/PerfectFit-project/virtual-coach-issues/issues/371
