### ISSUE TITLE
Exercises usefulness

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#50]
Is it correct that exercises that were useful are repeatedly shown when using oefening? That would make sense, but if only exercises that haven't been done yet are shown something goes wrong (I got a few from my first aid kit)

Tester: Eline

**Comment by wbaccinelli** [comment]
All the exercises available in the specific phase or day the user is in are listed. The availability is specified in the [contents bible](https://leidenuniv1.sharepoint.com/:x:/r/sites/TeamAio/_layouts/15/Doc.aspx?sourcedoc=%7B1B69D6E4-49AA-438A-B3F2-602CEDBBFF9E%7D&file=2022.10.10_Perfect%20Fit%20app%20bible%20(Content%20overview%20and%20planning).xlsx&action=default&mobileredirect=true&cid=b774abbb-b295-44f1-9de1-b6a63e559ddc)
Please, let me know if I am interpreting the question correctly.

**Comment by aversluis1** [comment]
@wbaccinelli, I tested myself to see what Eline was referring to. And what I noticed when doing 'oefening' is that you can indeed choose from all activities that are listed in the bible for a specific day. However, if you do two exercises after each other. When choosing the second exercise, the exercise that you did before - is not in the list. Is that correct?

**Comment by wbaccinelli** [comment]
@aversluis1 yes, that's correct. This can be changed, I don't really remember why it has been set like this. Shall we show also the last executed exercise?

**Comment by aversluis1** [comment]
I think this was decided because we want people to do different exercises, and not just choose the same one every time (although I doubt people will actually do this). 

If it is just the last exercise that is not shown, I think we can keep it like this.

**Comment by wbaccinelli** [comment]
Let's keep it like this than.
