### ISSUE TITLE
sorry menu during exercsie

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#51]
Sorry menu should not start during an exercise

**Comment by wbaccinelli** [comment]
It should not indeed, but I am missing a bit of context. I guess it refers to [this other issue](https://github.com/PerfectFit-project/testing-tickets/issues/52)?

**Comment by aversluis1** [comment]
Yes that is correct. So if a user is in a dialog or exercise and does not give the correct answer (or an answer is not expected), than the sorry menu should not start.

**Comment by wbaccinelli** [comment]
Yes yes, but this case was a synch case. The exercise was already over, but not correctly visualized in the app.
