### ISSUE TITLE
Volhouden exercise 

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#52]
30/7 22.01 Volhouden exercise was only 1 message and seemed incomplete, see screenshot . Only first paragraph is shown (of the 3)

![Screenshot_20230730-220445](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/caf8d2e6-edfd-47f3-bd77-11ae7c30ea74)

For the Volhouden exercise the persuasion sentence did not seem to align very well, I had this: Het grootste deel van de mensen gelooft dat deze oefening zal helpen om ... om vol te houden, ook als veel mensen om je heen roken of niet veel bewegen
This should be 'om' instead of 'om... om'. I think it's useful to check this for all the persuasive messages

**Comment by wbaccinelli** [comment]
This looks again like a synchronization error in the app (already mentioned to NiceDay). This is what I see in the web app:
![image](https://github.com/PerfectFit-project/testing-tickets/assets/100706999/e80a9366-6d07-4d00-888b-70777abd8fba)

**Comment by aversluis1** [comment]
Any idea when this issue will be fixed by Niceday?

**Comment by wbaccinelli** [comment]
Unfortunately not

**Comment by wbaccinelli** [comment]
The developers in NiceDay are now able to reproduce the error and they plan to fix this in around 4 weeks from now. 

NiceDay ticket issue #6872
