### ISSUE TITLE
EHBO rating 

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#54]
Is it correct that exercises with a usefulness rating of 5 get in your ehbo doos? that just happened to me, but I find it not so logical as the grade is pretty low. 

![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/d2af78cd-08d1-49f9-8a64-ac72ce25363a)

**Comment by wbaccinelli** [comment]
If there are less than 5 items in the ehbo, the rating is still in the top 5 scores even if it is low, so it is added.

**Comment by aversluis1** [comment]
ok!
