### ISSUE TITLE
Goal setting dialog: timing

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#55]
@wbaccinelli, Eline and me were wondering about the timing of the goal setting dialog. Is it correct that this is scheduled to occur on the 10th day of the preparation phase? 

If so, we find it illogcial to not talk about goals and a quite date sooner (because that is why people download the app). I think it is scheduled like this, because of the tracking period for steps, right? However, this tracking period is I think not needed for smoking and only a longer preparation period is needed for participants who want to use medicaiton (and this will be a smaller group). 

Would it be possible / feasible to make changes to the timing: for example, do the goal setting in the beginning after medication video (maybe only for smoking) and then do the goal setting for PA after the 9 tracking days? 

We are aware this might require big changes, but we are afraid the intervention is illogical otherwise and might not produce the desired effects. 

One other point: I am currently in day 9. Should I not get something today about the future self today? Because I haven't had anything yet (and I scheduled that I am available for exercises etc in  the morning).

**Comment by wbaccinelli** [comment]
@aversluis1 yes, that is correct. This would be quite a big change, and I really think that if this is not a super top priority, we should not go in this way at this point, given the fixes we still have to do and the limited amount of time left. Do I understand correctly that you would like to split a dialog and propose it in two different times? 


You should have received the dialog today, correct.

**Comment by aversluis1** [comment]
As discussed, you can close this item!
