### ISSUE TITLE
Reaction that user found activity useful when that is not the case in general activity dialog

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/testing-tickets#57]
I evaluated my past activity with "2", but still got the message that I found the activity useful and that it is thus placed in my first-aid-kit. This should only happen when the score is in the top 5.

![WhatsApp Image 2023-08-02 at 6 53 00 AM](https://github.com/PerfectFit-project/testing-tickets/assets/43779515/3fdf2932-1ce3-44b9-a2a5-d9e0450df3c9)

**Comment by wbaccinelli** [comment]
@nelealbers If you have less than 5 activities in your ehbo, the score is always in the top 5

**Comment by nelealbers** [comment]
@wbaccinelli I see, but then the reaction sounds very strange. It says "You find the activity useful, so we add it to your first-aid-kit". That is a weird thing to say when I just rated the activity as unuseful. It would be good to adapt the response then, maybe with conditional response variation depending on whether the usefulness rating is also greater than 5 or not.
