### ISSUE TITLE
HRS dialog

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#59]
Tester Eline

Not sure whether verder works correctly now. On 4/8 I started the hrs dialog and typed 3 to indicate that I did not need help, but when I typed verder on 5/8 I got the general activity dialog. See screenshot 

![Screenshot_20230805-083150](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/5a14e882-394d-4758-81fe-2686aee3f55a)

**Comment by wbaccinelli** [comment]
I see no errors here. The dialogs expire after a while and if something is typed, as usual, the menu is shown. It is also this case (this is not the general activity dialog). Am I missing something?

**Comment by aversluis1** [comment]
You are right. I did not check the message from Eline completely. She of course misses how the issues in the app are addressed, and I think she just didn't reaslise she answered "too late". And it is indeed not the general activity dialog. So you can ignore this message. 

However, @Milonvv , can you make sure that in the instruction to the participants - it is made clear that, when they don't answer soon enough, that the dialog doesn not continue --- but that they would have to press 'verder' and that it starts (in most cases) again from the beginnning?

**Comment by Milonvv** [comment]
@aversluis1 'Verder' is dus sowieso een nieuwe command begrijp ik hieruit? Want het lijstje met commands moet ook in de handleiding.

En daarnaast moet er dus uitgelegd worden dat dialogen na een bepaalde tijd 'verlopen' en dat wanneer ze dan 'verder' typen het dialoog waarschijnlijk weer vanaf het begin opstart?

**Comment by Milonvv** [comment]
@rvaneersel

**Comment by aversluis1** [comment]
> @aversluis1 'Verder' is dus sowieso een nieuwe command begrijp ik hieruit? Want het lijstje met commands moet ook in de handleiding.
> 
> En daarnaast moet er dus uitgelegd worden dat dialogen na een bepaalde tijd 'verlopen' en dat wanneer ze dan 'verder' typen het dialoog waarschijnlijk weer vanaf het begin opstart?

@Milonvv  @rvaneersel  Klopt inderdaad!
