### ISSUE TITLE
C1.14 scheduling preparation phase dialogues

### ISSUE THREAD

**Issue by emeijerperfectfit** [PerfectFit-project/testing-tickets#6]
kbolt@trimbos.nl 26-5-2023 12.28
e.meijer@lumc.nl 3-6-2023 20.41

The part shown in the excel file for C1.14 runs as intended, but Sam then continues with a video dialog in which no video link is sent. Probably as intended but just checking

**Comment by wbaccinelli** [comment]
Yes, this is intended. The dialog will never be launched alone. In this case it is not aware of which component has to be presented, so it sends an empty link.
