### ISSUE TITLE
persuasive messages

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#60]
Tester Eline: 

5/8 I got no persuasive message in the general activity dialog when I rated questions 2 and 3 very low, is that correct? I think so as I think I remember that we would do the persuasion only in half of the cases but not sure. See screenshot 
![Screenshot_20230805-120812](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/4cd7dad8-f58f-4546-a247-a5ad3c695db2)

**Comment by wbaccinelli** [comment]
@nelealbers I think that the flow is correct, right?

**Comment by nelealbers** [comment]
@wbaccinelli @aversluis1 I have not yet implemented the randomization for the persuasive messages (i.e., sending the optimal persuasive message only in 80% of the cases). This is low priority right now.

But even in the non-randomized case, the optimal persuasion in some situations is to not persuade (i.e., to not send a persuasive message). See the variable OPT_POLICY here: https://github.com/PerfectFit-project/virtual-coach-rasa/blob/main/Rasa_Bot/actions/definitions.py. So it is correct that in some cases, no persuasive message is sent.
