### ISSUE TITLE
Goal for PA

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#62]
Tester Eline

With the weekly goal for PA I indicated that I did not want to start intensive PA. Later I got this message: 
Het weekdoel is om dagelijks 8000 stappen te zetten 🚶🏿 en ten minste None minuten intensief te bewegen 🏊 🚴🤸
The None should not be there. I think we can best remove the second part of the sentence (from en ten minste inward) if people don't have an intensive PA goal, or we should replace this part with something like Je hebt deze week geen doel voor intensieve beweging.

**Comment by wbaccinelli** [comment]
As everything related to the sensors data, also this part is hardcoded, so the group assignment and the steps/intensity minutes are fake or None values. This needs to be tested with the sensors.

@bscheltinga can you check the first point ('With the weekly goal for PA I indicated that I did not want to start intensive PA.')?

**Comment by bscheltinga** [comment]
I see the confusion here! @aversluis1 I understand your intepration of the question. I looked at the excel file and think something else is meant with the question: 'Zie jij dit zitten'. In the column with logic for the programmers in the excel there is:

> Only one answer possible. If anything else than these numbers is typed, say 'Typ 1 of 2 om aan te geven of je komende week intensiever wilt gaan bewegen'. 
> If user types 1 (ja), continue to row 176. 
> Ik user types 2 (nee), continue to row 172. If user says no here, keep the same intensity goal as the previous week. 

So you chose option 2 (thinking you would not receive a goal for intensity), however, it is meant that the proposed goal in the sentence before, is not applied, but instead, you keep the intensity minutes goal of previous week. Especially, the first time people receive a goal for intensity minutes, this can be confusing.

So in the end, they receive a goal for intensity minutes, regardless they say yes/no to the question. However, if they say yes, the goal of the previous week is updated (increased with 15 minutes). If they say no, the goal remains the same as the week before.

This part of the dialog is implemented in accordance with the excel sheet.

**Comment by aversluis1** [comment]
@bscheltinga , okay, thanks for the explanation. Would it then make sense to adjust the answers, and elaborate a bit. For example, say 'ja, ik wil intensiever gaan bewegen' and 'nee, ik wil niet intensiever bewegen en ik behoud mijn intensiteitsdoel van vorige week'  ?
