### ISSUE TITLE
ehbo doos - rating usefulness

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#63]
I commented on this before, but in the beginning - when there are no exercises in the ehbo doos - it is a bit weird when low rated exercises end up in de box. 

Although I get it, it might be better to adjust the message that is send. So instead of saying 'great that this exercise is useful for you', we better leave this part out. 

I suggest the following. Instead of "Bedankt voor je reactie. Fijn dat deze oefening nuttig voor je is. Deze oefening wordt daarom toegevoegd aan je EHBO-doos."

We can say: "Bedankt voor je reactie. De oefening wordt toegevoegd aan je EHBO-doos."

**Comment by wbaccinelli** [comment]
Already covered [here](https://github.com/PerfectFit-project/virtual-coach-issues/issues/413)
