### ISSUE TITLE
Reflection dialog

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#65]
1. I had to answer the 'Wat maakt dat niet-roken goed ging' multiple times, because I hadn't used the necessary amount of words/characters. Not sure what the needed amount is, but maybe lower it a bit?

![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/21c57aa9-691a-4965-bfc7-766a02d24ce7)

2. I was shown a graph with the situation in which I find it difficult not to smoke. However, I hadn't given up any of these situations, so the graph is empty. Should this messag and the graph not be ommitted, if no situations were registered?

![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/825942c9-b334-41fa-b835-8fb6d0d83eb4)

3. The graph with the step overview is in English. Will this be in Dutch in the final version?
4. AFter the graph, I am asked the question what type of PA I did last week and a number of options are given. But instead of answering this question, I get answer options describing how well it went. See screenshot. 
![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/dca81110-3ef0-405c-b2c0-4e6083d144c8)

5. The goal of intense exercise is a bit strange. In the beginning of the reflection on PA, the step goal is listed (8000 -- is this a standard amount now used??) and 30 minutes of intense exercise ( I don't remember setting this amount?). AFter the graph with steps is shown, and then a dialogue follows wherein it is suggested that - in the next week - I move 30 minutes intensively. However, apparently (based on the first screenshot), I was already supposed to be doing that? 

![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/cae79d29-3f7a-4d6e-95c1-6a1d7f07b82d)
![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/2371e966-3a56-4f12-9867-4dfce21f1f46)

**Comment by wbaccinelli** [comment]
@aversluis1 
1. The user needs to input at least 5 words. Is this too much?
2. Changing the flow according to the situation is a bit difficult. If not extremely necessary, I would keep it as low priority
3. We definitely need to change this
4. I see, this is an error in the [excel file, line 114](https://leidenuniv1.sharepoint.com/:x:/r/sites/TeamAio/_layouts/15/Doc.aspx?sourcedoc=%7B84443391-2359-4F44-9500-2B6A62209139%7D&file=FOR%20SPRINT%20FEB%208%20---%20C1.17%20Weekly%20reflection%20dialog.xlsx&action=default&mobileredirect=true). 
5. All the data relying on the sensor information (steps, intensity minutes, PA group, goals, etc.) are hardcoded. Please, don't review them.

**Comment by aversluis1** [comment]
@wbaccinelli 
1. No that is not a lot, maybe I just entered a lot of characters. Sorry. Just ignore
2. Lets not change the flow, but maybe we could go for an easy fix and add a sentence "De grafiek is leeg als je nog geen situaties hebt opgegeven waarin het moeilijk was om niet te roken. 
3-5. Okay!
