### ISSUE TITLE
Timing within video dialogues

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#67]
I am now testing with an Android, and notice that the messages that are send after the link to the video appear much quicker (within the minute). So while I am still watching the video, I get messages asking me to judge whether the video is clear.

**Comment by wbaccinelli** [comment]
@aversluis1 yes, we discussed this with @emeijerperfectfit and now the new messages are sent 1 minute after the link

**Comment by aversluis1** [comment]
Ah okay!
