### ISSUE TITLE
Timing messages

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#68]
I got a message this morning to do an exercise at 6 AM. I believed we discussed this already, and that we agreed to schedule messages later in the morning. Or am I mistaken? Or maybe you haven't gotten around to it? Anyway, just thought I would post it here!

**Comment by wbaccinelli** [comment]
You're very right. They are supposed to not being sent before 8 a.m. What I see is that I didn't consider that the server time is GMT, so it is 2h earlier 🤦‍♂️. I should quickly fix it.

**Comment by aversluis1** [comment]
Haha, small detail!
