### ISSUE TITLE
PA Tracking past 9 days

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#69]
I started wearing the smartwatch last tuesday (August 15), now I just did the goal setting dialog (on March 21) and it says 'In de afgelopen 9 dagen zette je ongeveer .... stappen'. 

However, there are no 9 days in between these dates. so this appears to be wrong.

**Comment by nelealbers** [comment]
@aversluis1 This number 9 is hardcoded in the text (see [here](https://github.com/PerfectFit-project/virtual-coach-rasa/blob/main/Rasa_Bot/domain/domain_goal_setting_dialogs.yml)). I do not know enough about the intervention setup to say what needs to be done here. I hope @bscheltinga can take a look when he comes back next week.
