### ISSUE TITLE
C1.15 execution introduction video

### ISSUE THREAD

**Issue by emeijerperfectfit** [PerfectFit-project/testing-tickets#7]
tested by Sharifaadil@hotmail.com 26-05-2023 16:00

The message "Typ 1 voor duidelijk en 2 voor nog een keer bekijken" was sent too late

![image](https://github.com/PerfectFit-project/testing-tickets/assets/135458606/312d0384-0562-4127-a205-a0a44ed6484b)

**Comment by wbaccinelli** [comment]
This behavior is an app problem that has to be addressed by NiceDay. In the web app I see that the messages has been correctly delivered, but the app is not synched. 
![image](https://github.com/PerfectFit-project/testing-tickets/assets/100706999/61871c3d-9a37-4815-a0ea-ae94102d66ed)

**Comment by emeijerperfectfit** [comment]
That's annoying. Is it something that they plan to fix any time soon?

**Comment by wbaccinelli** [comment]
@bscheltinga can you see if you are able to reproduce and record the behavior?

**Comment by wbaccinelli** [comment]
Issue picked up by NiceDay.
