### ISSUE TITLE
End messages 'veranderingen in je lichaam'

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#70]
I did the exercise 'veranderingen in je lichaam' but I did not get the end messages that was (recently) added -- 'Dit is het einde van de oefening. '  Has it not been added yet or is it a fault?

**Comment by nelealbers** [comment]
@aversluis1 We have already fixed this but the virtual coach used for testing does not yet have this updated version.

**Comment by aversluis1** [comment]
Ah okay, thanks for letting me know
