### ISSUE TITLE
Typo in HRS dialog

### ISSUE THREAD

**Issue by Milonvv** [PerfectFit-project/testing-tickets#76]
Very minor textual issue:

In the HRS dialog, the fourth message of the dialog, is currently written "Typ '1' als je het gaat om roken.", but this should be "Typ '1' als het gaat om roken.' (without 'je').

![WhatsApp Image 2023-08-24 at 16 23 16](https://github.com/PerfectFit-project/testing-tickets/assets/91131769/f43b0927-b9fc-473d-a79f-bc55efbd9bd7)

**Comment by nelealbers** [comment]
@Milonvv Okay, I created an issue for this. Given the number of issues that now pop up on such a short notice, I am not sure if we will have time to fix all of these though.

**Comment by Milonvv** [comment]
@nelealbers Thanks, I understand and this is also very minor of course (:
