### ISSUE TITLE
Data smartwatch not transmitted?

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#77]
I have not been wearing my watch for a couple of days (as i did not get a step goal notification anyway), but as I can ask this using the command - I wore it again today. 

I got the message to take 6000 steps (which I think is the default if you  haven't tracked PA in a while - is that correct?). But at the end it said that the data does not come in accurately, see screenshot. It looks to me like the smartwatch is connected to the phone. Is there smoething wrong OR is it because i didn't wear the watch for a couple of days? (And the watch and phone were not in close proximity of each other)

![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/2625c793-d4eb-4909-bc0b-10f66b41a27d)

**Comment by nelealbers** [comment]
@bscheltinga can you take a look?

**Comment by bscheltinga** [comment]
> I got the message to take 6000 steps (which I think is the default if you haven't tracked PA in a while - is that correct?)

No, the default would be 2000, so the 6000 is not the default value but I expect it to be your adaptive goal.

The message: _"Het lijkt er op dat de data van de smartwatch helaas niet goed binnenkomt. Neem contact op met de onderzoeker."_ is shown if the data for the last 3 days (untill yesterday) is: (1) not present or (2) <1000 steps per day. 

Normally, after the step goal is given, it will give a warning when the daily goal is given, if yesterday no data is present or the step count is <1000: _"Vergeet vandaag niet om het horloge om te doen en controleer of bluetooth op de telefoon aan staat. Mocht je even niet meer weten hoe je dit doet? Kijk dan in de handleiding die je van onderzoekers gekregen hebt of neem contact op met de onderzoekers voor hulp."_

You can check whether the data is present by running the /EXTERNAL_reflection_dialog untill you receive the bar diagram with realized steps and goals. In this bar plot, it is easy to identify missing data. Please let me know what your result :)

**Comment by aversluis1** [comment]
@bscheltinga , thansk for your elaboration! I ran the command '/EXTERNAL_reflection_dialog', however, I doesnt start the dialog - it just gives options for me to do (the code words). Is it the correct command?

**Comment by bscheltinga** [comment]
Sorry, the command should be /EXTERNAL_weekly_reflection (as I send in the meeting yesterday..)

**Comment by aversluis1** [comment]
I ran both codes today, and when I asked for the step goal - it now didn't show the message that data was not collected correctly. Plus my step goal was higher agani. 

The weekly reflection dialog also worked. See below the graph that was given. It had four days of missed data. 

![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/fc4b615e-3859-4136-95c7-fb19edd33292)
So I think all is going correctly.

**Comment by bscheltinga** [comment]
Thanks for the update! Looks good and well done on the >10.000 steps ;)

**Comment by aversluis1** [comment]
haha thanks!
