### ISSUE TITLE
Weekly reflectiond dialog - double message

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#78]
In the weekly reflection dialog (self started), I answered with too little words and then I got asked to write more words. And also a message that was I think a repetition of the earlier messsage 'Mooi! :) ....'  , and this should not have been shown.  

![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/fafeb12f-83e2-4446-9706-fe6f8c32cc10)

**Comment by nelealbers** [comment]
@aversluis1 This is expected behavior. The original question asked is repeated when not enough words are entered as response. In this case, it sounds a bit strange because the question message also consists of the "mooi/geweldig"-part. To avoid this, the question could be split into two messages, i.e., one with "mooi/geweldig" and then another message with the actual question. Then the repetition would sound less strange.

**Comment by aversluis1** [comment]
@nelealbers, ah I see - but in that case, I would prefer to leave out the first message saying 'kun je dat ....' and change the second message to 'Geweldig :) Kun je in iets meer woorden uitleggen waarom het zo goed ging met jouw beweging deze week?

**Comment by nelealbers** [comment]
@aversluis1 Your suggestion does not work. The question that is repeated is the exact same one as is asked first (just with a different formulation here).

The flow is like this:
Utterance 1: Mooi - wat maakt dat het zo goed ging met bewegen?
User: xxx
Utterance too short: Zou je dat in meer woorden kunnen omschrijven?
Utterance 1: Mooi - wat maakt dat het zo goed ging met bewegen?

Utterance 1 will always be repeated when the user input is not valid, so it needs to make sense both the first time it is uttered (i.e., when the user is first asked the question) and when the user gives a non-valid response.

How we solved this is to remove the "Mooi" from Utterance 1 to make it sound less strange when it is repeated. That is all we can do here:
Utterance 0: Mooi!
Utterance 1: Wat maakt dat het zo goed ging met bewegen?
User: xxx
Utterance too short: Zou je dat in meer woorden kunnen omschrijven?
Utterance 1: Wat maakt dat het zo goed ging met bewegen?

**Comment by aversluis1** [comment]
@nelealbers, thanks for the explanation. Your change sounds like a perfect solution!
