### ISSUE TITLE
Double message

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#81]
In the weekly reflection dialog there was a double message telling me I should typ 'klaar' when I am ready. (Differently formulated though ;)) See screenshot. 

![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/3a60cc0a-8e13-4fd9-9190-4c4e571bb937)

**Comment by wbaccinelli** [comment]
@aversluis1 when the user input is not correct, the first question is repeated. This is the same as [this issue](https://github.com/PerfectFit-project/testing-tickets/issues/78).

We can split the formulation also in this case.

**Comment by aversluis1** [comment]
@wbaccinelli , I figured it was the same as that issue indeed. It is also fine to just repeat the question but then the first message 'Typ klaar als je hier klaar mee bent'  can then be removed.
