### ISSUE TITLE
Future-selves short video

### ISSUE THREAD

**Issue by Milonvv** [PerfectFit-project/testing-tickets#85]
During testing, on day 4, the coach started the 'short dialog for presenting video's' with the short future-selves video (at 10.00). However, I received the dialog 4 times.

![Screenshot_20230915_123949_NiceDay](https://github.com/PerfectFit-project/testing-tickets/assets/91131769/f337097f-eac4-4a97-8723-933d0ab7d4d2)

**Comment by wbaccinelli** [comment]
Yes, there was an error (the same that prevented the scheduled activity to be sent). Addressed [here](https://github.com/PerfectFit-project/virtual-coach-rasa/blob/82400beb3ba9690a9790def96cb7a31391b10e6e/scheduler/state_machine/state_machine_utils.py#L810)
