### ISSUE TITLE
Future-selves short video repeats after completing, when typing 'verder'

### ISSUE THREAD

**Issue by Milonvv** [PerfectFit-project/testing-tickets#86]
On day 4 (15 September), I completed the dialog for presenting video's with the short version of the future-selves video (I let the coach know that I understood the video by typing '1'). After that, the coach sent me the standard messages with the different commands (e.g., verder, oefening, medicatie). I typed the command 'verder' as I was curious what would happen, since I already completed the previous dialog (the short future selves video). After that, the coach sent the dialog for presenting video's with the short version of the future-selves video again. 

This could be repeated over and over again, even though I already completed this short FS video dialog. Is that supposed to happen?
![Screenshot_20230918_161747_NiceDay](https://github.com/PerfectFit-project/testing-tickets/assets/91131769/0e71621a-7c95-4436-9046-16f7a4c9a1b7)
![Screenshot_20230918_161754_NiceDay](https://github.com/PerfectFit-project/testing-tickets/assets/91131769/c690e489-d899-4bc0-ba6c-ac44ea0462fd)
![Screenshot_20230918_161802_NiceDay](https://github.com/PerfectFit-project/testing-tickets/assets/91131769/7ef3f0c7-9509-47f8-a67a-83845a638456)

**Comment by wbaccinelli** [comment]
@Milonvv No, that's not supposed to work like this. It's all related to the same issue that you experienced with the [repetition of utterances](https://github.com/PerfectFit-project/testing-tickets/issues/85). Due to the error, the dialog has been recorded in the DB multiple times. I fixed this manually.
