### ISSUE TITLE
No notifications on quit day and about daily step goal/amount of steps taken

### ISSUE THREAD

**Issue by Milonvv** [PerfectFit-project/testing-tickets#87]
I completed the goalsetting dialog on Monday 18 September, and let the coach know that I wanted to quit smoking on the day after (19-09-2023). However, I did not receive notifications about my quit date on 19 September.

I also do not receive notifications about my step goal and the amount of steps taken.

**Comment by wbaccinelli** [comment]
@Milonvv You're right, there's an edge case I didn't consider. If the first aid kit video is not completed, we don't move to the next phase. But I see that if the quit date occurs and the video has not been seen, there is a problem. Shall we make the completion of the video dialog not mandatory?

**Comment by Milonvv** [comment]
@wbaccinelli  Yes, I think that is a good idea! They can always use the word 'uitleg' in the execution phase to see the First Aid Kit video in case they missed it.
